/* ===== 内置数据：动作库 / 备课专项 / 新闻样例 / 真实文献种子 ===== */
App.data = {};

/* ---------- 1. 动作库（市面常见练习） ---------- */
App.data.exercises = [
  // —— 体态训练 ——
  { id:'ex_wallangel', name:'靠墙天使', cat:'体态', face:'🧱', target:'肩袖/胸椎', level:'初级', equip:'无', age:['通用','青少年','成人'],
    steps:['脚后跟、臀、肩、头贴墙，双臂屈肘90°贴墙','吸气上举双臂成"W→Y"，缓慢上下滑动10次'], tips:'保持腰椎贴墙，避免塌腰代偿。' },
  { id:'ex_band_er', name:'弹力带肩外旋', cat:'体态', face:'💪', target:'冈下肌/小圆肌', level:'初级', equip:'弹力带', age:['通用','成人'],
    steps:['屈肘90°夹毛巾于腋下，双手拉弹力带向外旋转','缓慢回放，12次×3组'], tips:'改善圆肩，强化后侧肩袖。' },
  { id:'ex_chintuck', name:'收下巴训练', cat:'体态', face:'📱', target:'颈深屈肌', level:'初级', equip:'无', age:['通用','青少年','成人'],
    steps:['坐直，手指抵下巴向后推，做出"双下巴"','保持5秒，重复10次'], tips:'针对脖子前倾（头前伸），别仰头。' },
  { id:'ex_catcow', name:'猫牛式', cat:'体态', face:'🐱', target:'脊柱/胸椎', level:'初级', equip:'无', age:['通用','老年','成人'],
    steps:['四足跪姿，吸气塌腰抬头（牛），呼气弓背低头（猫）','缓慢交替，每侧停留3秒，10次'], tips:'改善驼背与脊柱灵活度。' },
  { id:'ex_pec_stretch', name:'胸小肌门框拉伸', cat:'体态', face:'🚪', target:'胸小肌', level:'初级', equip:'无', age:['通用','成人'],
    steps:['前臂贴门框，身体缓慢前倾','保持30秒，左右各2组'], tips:'圆肩人群每日必做。' },
  { id:'ex_ytwl', name:'YTWL肩屈训练', cat:'体态', face:'🔤', target:'斜方肌中下束', level:'中级', equip:'弹力带', age:['青少年','成人'],
    steps:['俯身，双臂依次摆出Y、T、W、L字母','每个姿势停顿1秒，10次'], tips:'强化背部，拉开肩带。' },
  { id:'ex_deadbug', name:'死虫式', cat:'体态', face:'🐛', target:'核心/骨盆', level:'初级', equip:'无', age:['通用','成人'],
    steps:['仰卧举臂举腿90°，对侧手脚缓慢下放','保持腰贴地，12次×3'], tips:'改善骨盆前倾与核心稳定。' },
  { id:'ex_bridge', name:'臀桥', cat:'体态', face:'🌉', target:'臀大肌/竖脊肌', level:'初级', equip:'无', age:['通用','老年','成人'],
    steps:['仰卧屈膝，臀发力顶起至肩髋膝一线','顶峰夹臀2秒，15次'], tips:'强化臀与下背，缓解久坐腰痛。' },

  // —— 有氧训练 ——
  { id:'ex_jog', name:'慢跑', cat:'有氧', face:'🏃', target:'心肺', level:'初级', equip:'跑鞋', age:['青少年','成人','老年'],
    steps:['热身5分钟后以能说话的配速慢跑','每次20-40分钟，每周3-5次'], tips:'减脂首选，注意跑姿与落地。' },
  { id:'ex_rope', name:'跳绳', cat:'有氧', face:'🪢', target:'心肺/协调', level:'中级', equip:'跳绳', age:['儿童','青少年','成人'],
    steps:['前脚掌着地，肘贴身小幅度摇绳','间歇跳：跳1分钟休30秒，循环10组'], tips:'高效燃脂，膝盖不适者减量。' },
  { id:'ex_swim', name:'游泳', cat:'有氧', face:'🏊', target:'全身心肺', level:'初级', equip:'泳具', age:['通用'],
    steps:['任选泳姿，保持匀速','每次30分钟以上'], tips:'低冲击，关节友好，体态/减脂皆宜。' },
  { id:'ex_bike', name:'骑行', cat:'有氧', face:'🚴', target:'下肢心肺', level:'初级', equip:'自行车', age:['通用','老年'],
    steps:['中等阻力匀速骑行','40分钟以上，心率维持120-150'], tips:'通勤亦可，保护膝关节。' },
  { id:'ex_walk', name:'快走', cat:'有氧', face:'🚶', target:'心肺', level:'初级', equip:'无', age:['老年','通用'],
    steps:['挺胸收腹，手臂自然摆动','每天6000-8000步'], tips:'最安全的有氧，老年友好。' },
  { id:'ex_hiit_run', name:'HIIT间歇跑', cat:'有氧', face:'⚡', target:'心肺/代谢', level:'高级', equip:'无', age:['青少年','成人'],
    steps:['慢跑1分钟+冲刺30秒，循环8-10组','每周2次，间隔48小时'], tips:'高效提升VO2max与燃脂，需有基础。' },
  { id:'ex_elliptical', name:'椭圆机', cat:'有氧', face:'🌀', target:'心肺', level:'初级', equip:'器械', age:['通用','老年'],
    steps:['双手扶把，前后交替蹬踏','20-30分钟中等阻力'], tips:'无冲击，孕期/康复可用。' },

  /* ===== 无氧/力量（按身体部位细分） ===== */
  // —— 腿部 ——
  { id:'ex_squat', name:'徒手深蹲', cat:'无氧', part:'腿', face:'🦵', target:'股四头/臀', level:'初级', equip:'无', age:['通用','青少年','成人'],
    steps:['双脚与肩同宽，臀向后坐 like坐椅','膝不内扣，蹲至大腿平行，12次×3'], tips:'力量训练基石，注意重心在足中。' },
  { id:'ex_lunge', name:'弓步蹲', cat:'无氧', part:'腿', face:'🚶', target:'臀腿', level:'初级', equip:'无', age:['通用','成人'],
    steps:['向前迈步下蹲至双膝90°','交替腿，每侧10次'], tips:'改善左右不平衡。' },
  { id:'ex_bss', name:'保加利亚分腿蹲', cat:'无氧', part:'腿', face:'🦵', target:'单腿/臀', level:'中级', equip:'凳/无', age:['成人','青少年'],
    steps:['后脚搭凳，前腿下蹲至90°','每侧10次×3'], tips:'强化单侧力量，改善不平衡。' },
  { id:'ex_legext', name:'腿屈伸', cat:'无氧', part:'腿', face:'🦵', target:'股四头', level:'初级', equip:'器械', age:['成人','老年'],
    steps:['坐器械，小腿向前伸','缓慢回放，12次×3'], tips:'孤立练股四，膝痛轻重量。' },
  { id:'ex_calf', name:'提踵', cat:'无氧', part:'腿', face:'🦶', target:'小腿', level:'初级', equip:'无/哑铃', age:['通用','成人'],
    steps:['站台阶边缘，踮脚至最高点','缓慢下落，15次×3'], tips:'强化小腿，防踝伤。' },
  { id:'ex_goblet', name:'高脚杯深蹲', cat:'无氧', part:'腿', face:'🏆', target:'股四头/臀', level:'中级', equip:'哑铃/壶铃', age:['成人','青少年'],
    steps:['双手捧铃于胸前，下蹲至大腿平行','保持躯干直立，12次×3'], tips:'改善深蹲姿态，强化前侧。' },
  { id:'ex_stepup', name:'登阶训练', cat:'无氧', part:'腿', face:'🪜', target:'臀腿/协调', level:'初级', equip:'凳/台阶', age:['通用','成人'],
    steps:['一脚踩凳，伸膝伸髋站起','控制回落，每侧12次×3'], tips:'模拟上台阶，强化臀腿。' },

  // —— 臀部 ——
  { id:'ex_hipthrust', name:'臀推', cat:'无氧', part:'臀', face:'🍑', target:'臀大肌', level:'中级', equip:'哑铃/杠铃', age:['成人'],
    steps:['上背靠凳，杠铃置髋','顶髋至身体平直，顶峰夹臀，12次'], tips:'练臀高效动作。' },
  { id:'ex_slbridge', name:'单腿臀桥', cat:'无氧', part:'臀', face:'🌉', target:'臀/核心', level:'中级', equip:'无', age:['通用','成人'],
    steps:['仰卧单腿屈，另一腿伸直','臀发力顶起，每侧12次'], tips:'进阶臀桥，改善左右失衡。' },
  { id:'ex_firehydrant', name:'消防栓式', cat:'无氧', part:'臀', face:'🐕', target:'臀中肌', level:'初级', equip:'无', age:['通用','成人'],
    steps:['四足跪姿，屈膝向外打开至髋水平','控制回落，每侧15次×3'], tips:'改善髋外展与臀中肌。' },
  { id:'ex_donkeykick', name:'驴踢', cat:'无氧', part:'臀', face:'🦵', target:'臀大肌', level:'初级', equip:'无', age:['成人'],
    steps:['四足跪姿，屈膝向后上方蹬伸','顶峰夹臀，每侧15次×3'], tips:'孤立刺激臀部。' },
  { id:'ex_clam', name:'蚌式开合', cat:'无氧', part:'臀', face:'🐚', target:'臀中肌/髋外旋', level:'初级', equip:'弹力带', age:['通用','成人'],
    steps:['侧卧屈膝，双脚并拢，打开上方膝','顶峰停留2秒，每侧15次×3'], tips:'改善膝内扣与臀中肌。' },

  // —— 背部 ——
  { id:'ex_pullup', name:'引体向上', cat:'无氧', part:'背', face:'🧗', target:'背阔肌', level:'高级', equip:'单杠', age:['青少年','成人'],
    steps:['握杠悬垂，背阔发力拉至下巴过杠','做不到用弹力带辅助'], tips:'练背王牌。' },
  { id:'ex_dl', name:'哑铃硬拉', cat:'无氧', part:'背', face:'🏋️', target:'腘绳/臀/背', level:'中级', equip:'哑铃', age:['青少年','成人'],
    steps:['屈髋屈膝握铃，背部挺直','臀发力顶起，12次×3'], tips:'腰背中立，勿圆背。' },
  { id:'ex_row', name:'哑铃划船', cat:'无氧', part:'背', face:'🚣', target:'背阔/斜方肌中束', level:'中级', equip:'哑铃', age:['成人','青少年'],
    steps:['单手持哑铃，另一手膝撑凳，背部平直','肘贴近身体向后上方拉，每侧12次×3'], tips:'别用腰部借力，肩胛后收。' },
  { id:'ex_latpulldown', name:'高位下拉', cat:'无氧', part:'背', face:'⬇️', target:'背阔肌', level:'中级', equip:'器械', age:['成人'],
    steps:['宽握横杆，肩胛下沉后拉至锁骨','控制回放，12次×3'], tips:'避免耸肩与过度后仰。' },
  { id:'ex_facepull', name:'面拉', cat:'无氧', part:'背', face:'🎯', target:'后肩/菱形肌', level:'初级', equip:'弹力带/绳索', age:['成人','青少年'],
    steps:['双手拉绳至面部两侧，拇指朝后','顶峰夹肩胛，15次×3'], tips:'改善圆肩，强化后侧。' },
  { id:'ex_superman', name:'超人式', cat:'无氧', part:'背', face:'🦸', target:'竖脊肌/臀', level:'初级', equip:'无', age:['通用','成人'],
    steps:['俯卧，同时抬起双臂与双腿','顶峰停留2秒，12次×3'], tips:'强化下背与臀，注意幅度。' },

  // —— 胸部 ——
  { id:'ex_pushup', name:'俯卧撑', cat:'无氧', part:'胸', face:'💥', target:'胸/三头/肩', level:'中级', equip:'无', age:['青少年','成人'],
    steps:['核心收紧，身体成板','下降至上胸近地，推起，10次×3'], tips:'做不了可跪姿或推墙。' },
  { id:'ex_cablefly', name:'龙门架夹胸', cat:'无氧', part:'胸', face:'🦋', target:'胸肌', level:'中级', equip:'器械', age:['成人'],
    steps:['双手握把由两侧向内夹','顶峰夹胸，12次×3'], tips:'胸肌孤立训练。' },
  { id:'ex_chestpress', name:'哑铃卧推', cat:'无氧', part:'胸', face:'🛏️', target:'胸大肌/三头', level:'中级', equip:'哑铃/凳', age:['成人'],
    steps:['仰卧，哑铃推至胸上方，缓慢下落至胸侧','10-12次×3'], tips:'控制离心，肘约75°。' },
  { id:'ex_dips', name:'双杠臂屈伸', cat:'无氧', part:'胸', face:'🪜', target:'下胸/三头', level:'高级', equip:'双杠', age:['青少年','成人'],
    steps:['双臂支撑，身体前倾下降再推起','8-12次×3'], tips:'下胸刺激强，肩痛者慎做。' },

  // —— 肩部 ——
  { id:'ex_press', name:'哑铃推举', cat:'无氧', part:'肩', face:'🤸', target:'肩', level:'中级', equip:'哑铃', age:['成人'],
    steps:['坐姿，哑铃置于肩','垂直推至头顶，控制下落'], tips:'肩袖不适减小重量。' },
  { id:'ex_latraise', name:'侧平举', cat:'无氧', part:'肩', face:'↔️', target:'三角肌中束', level:'初级', equip:'哑铃', age:['成人'],
    steps:['双臂微屈向两侧平举至肩高','顶峰停顿，12次×3'], tips:'练肩宽度，勿耸肩。' },
  { id:'ex_frontraise', name:'前平举', cat:'无氧', part:'肩', face:'⬆️', target:'三角肌前束', level:'初级', equip:'哑铃', age:['成人'],
    steps:['双臂微屈向前平举至肩高','控制下落，12次×3'], tips:'前束孤立训练。' },
  { id:'ex_reardelt', name:'俯身飞鸟', cat:'无氧', part:'肩', face:'🦅', target:'三角肌后束', level:'中级', equip:'哑铃', age:['成人'],
    steps:['俯身，双臂微屈向两侧打开','顶峰夹肩胛，15次×3'], tips:'强化后肩，改善圆肩。' },
  { id:'ex_arnoldpress', name:'阿诺德推举', cat:'无氧', part:'肩', face:'🏋️', target:'三角肌整体', level:'中级', equip:'哑铃', age:['成人'],
    steps:['掌心朝内起手，外旋同时推至头顶','10-12次×3'], tips:'综合肩部训练。' },

  // —— 手臂 ——
  { id:'ex_curl', name:'哑铃二头弯举', cat:'无氧', part:'手臂', face:'💪', target:'肱二头', level:'初级', equip:'哑铃', age:['成人'],
    steps:['掌心向上持铃，弯举至肩前','控制下落，12次×3'], tips:'肘部固定不晃。' },
  { id:'ex_tri', name:'三头下压', cat:'无氧', part:'手臂', face:'🔻', target:'肱三头', level:'初级', equip:'弹力带/器械', age:['成人'],
    steps:['双手拉绳向下伸直','缓慢回放，12次×3'], tips:'改善"拜拜肉"。' },
  { id:'ex_hammercurl', name:'锤式弯举', cat:'无氧', part:'手臂', face:'🔨', target:'肱肌/前臂', level:'初级', equip:'哑铃', age:['成人'],
    steps:['掌心相对，弯举至肩前','控制下落，12次×3'], tips:'强化肱肌与前臂。' },
  { id:'ex_tridips', name:'凳上臂屈伸', cat:'无氧', part:'手臂', face:'🪑', target:'肱三头', level:'中级', equip:'凳', age:['成人'],
    steps:['双手撑凳边缘，屈肘下降再伸直','12次×3'], tips:'三头经典自重动作。' },
  { id:'ex_plank', name:'平板支撑', cat:'无氧', part:'核心', face:'🧱', target:'核心', level:'初级', equip:'无', age:['通用','成人'],
    steps:['前臂撑地，身体成直线','收紧腹部臀部，坚持30-60秒'], tips:'避免塌腰翘臀。' },
  { id:'ex_crunch', name:'卷腹', cat:'无氧', part:'核心', face:'🌀', target:'腹直肌', level:'初级', equip:'无', age:['通用','成人'],
    steps:['仰卧屈膝，腹发力卷起肩胛离地','缓慢下落，15次×3'], tips:'别用脖子代偿。' },
  { id:'ex_hangleg', name:'悬垂举腿', cat:'无氧', part:'核心', face:'🪝', target:'下腹', level:'高级', equip:'单杠', age:['青少年','成人'],
    steps:['悬垂，卷腹抬腿至水平','控制下落，10次'], tips:'核心进阶，别摆荡。' },
  { id:'ex_kbswing', name:'壶铃摆荡', cat:'无氧', part:'臀', face:'🔔', target:'臀/后链', level:'中级', equip:'壶铃', age:['青少年','成人'],
    steps:['屈髋握铃，臀发力向前摆至肩高','借髋而非手臂，15次×3'], tips:'爆发力+有氧结合。' },

  /* ===== 体能训练（分年龄段） ===== */
  { id:'ex_jack', name:'开合跳', cat:'体能', face:'⭐', target:'全身/协调', level:'初级', equip:'无', age:['通用','儿童','青少年'],
    steps:['跳起同时双臂上举、双脚分开','落地还原，30秒×4'], tips:'热身或体能循环常用。' },
  { id:'ex_burpee', name:'波比跳', cat:'体能', face:'🔥', target:'全身爆发', level:'高级', equip:'无', age:['青少年','成人'],
    steps:['下蹲撑地→后跳成板→俯卧撑→收腿→纵跳','8-10次×4组'], tips:'燃脂体能王，心脏不好减量。' },
  { id:'ex_highknee', name:'高抬腿', cat:'体能', face:'🦵', target:'下肢/心肺', level:'初级', equip:'无', age:['通用','儿童'],
    steps:['原地快速提膝至腰高','30秒快做×4'], tips:'跑动体能好动作。' },
  { id:'ex_farmer', name:'农夫行走', cat:'体能', face:'🚜', target:'握力/核心', level:'中级', equip:'哑铃', age:['成人'],
    steps:['双手各持重物，挺胸行走30-40米','2-3趟'], tips:'提升全身刚度与握力。' },
  { id:'ex_animal', name:'动物爬行', cat:'体能', face:'🐯', target:'核心/协调', level:'初级', equip:'无', age:['儿童'],
    steps:['熊爬/蟹爬/青蛙跳，趣味移动','每种10米'], tips:'儿童体能游戏化首选。' },
  { id:'ex_1leg', name:'单脚平衡站', cat:'体能', face:'🧍', target:'平衡/本体', level:'初级', equip:'无', age:['老年','通用'],
    steps:['单脚站立，双眼睁开→闭眼','每侧30秒×3'], tips:'防跌倒训练基础。' },
  { id:'ex_chairsit', name:'椅子坐站', cat:'体能', face:'🪑', target:'腿力/平衡', level:'初级', equip:'椅子', age:['老年'],
    steps:['双臂抱胸，从椅站起再坐下','10次×3'], tips:'老人居家练腿力。' },
  { id:'ex_throw', name:'抛接球游戏', cat:'体能', face:'⚾', target:'协调/反应', level:'初级', equip:'球', age:['儿童'],
    steps:['与家长/同伴对抛接','变化距离与高度'], tips:'趣味体能+社交。' },
  { id:'ex_slide', name:'侧弓步', cat:'体能', face:'↔️', target:'内收/臀', level:'初级', equip:'无', age:['通用','成人'],
    steps:['向侧迈步下蹲，重心在蹬伸腿','左右交替10次'], tips:'改善下肢灵活。' },
  { id:'ex_mountain', name:'登山者', cat:'体能', face:'⛰️', target:'核心/心肺', level:'中级', equip:'无', age:['青少年','成人'],
    steps:['平板姿势，快速交替提膝向胸','30秒×4'], tips:'核心+有氧结合。' },
  { id:'ex_russian', name:'俄罗斯转体', cat:'体能', face:'🔄', target:'腹斜肌', level:'中级', equip:'无/药球', age:['成人'],
    steps:['坐姿后倾，双腿微抬，左右转体触地','20次'], tips:'练腹斜与旋转稳定。' },

  // —— 体态训练（补充） ——
  { id:'ex_thoracic', name:'胸椎旋转拉伸', cat:'体态', face:'🌀', target:'胸椎灵活', level:'初级', equip:'无', age:['通用','成人','老年'],
    steps:['坐姿，右手抱椅背，左手扶膝','吸气延展，呼气向右旋转，停留5秒','左右各8次'], tips:'改善胸椎僵硬与代偿性腰痛。' },
  { id:'ex_foam_t', name:'泡沫轴胸椎放松', cat:'体态', face:'🧽', target:'胸椎/背阔', level:'初级', equip:'泡沫轴', age:['通用','成人'],
    steps:['仰卧将泡沫轴垫于上背','双手抱头，缓慢上下滚动30秒'], tips:'放松竖脊肌，缓解圆肩。' },
  { id:'ex_neck_lat', name:'颈侧屈拉伸', cat:'体态', face:'🤸', target:'颈侧肌群', level:'初级', equip:'无', age:['通用','青少年','成人'],
    steps:['坐直，右手垂于体侧','左手扶头向右轻拉，停留20秒','左右各2组'], tips:'缓解脖子前倾导致的颈肩紧张。' },
  { id:'ex_birddog', name:'鸟狗式', cat:'体态', face:'🐦', target:'核心/腰背', level:'初级', equip:'无', age:['通用','成人','老年'],
    steps:['四足跪姿，对侧伸手抬腿至水平','保持2秒，缓慢还原','每侧10次'], tips:'改善腰痛与核心稳定，避免塌腰。' },
  { id:'ex_shortfoot', name:'足弓激活（短足）', cat:'体态', face:'🦶', target:'足底/踝', level:'初级', equip:'无', age:['通用','青少年','成人'],
    steps:['坐姿/站姿，大脚趾压地，球部内收上提足弓','保持5秒，重复12次'], tips:'改善扁平足与下肢力线。' },
  { id:'ex_wallslide', name:'靠墙滑动', cat:'体态', face:'🧱', target:'肩胛活动度', level:'初级', equip:'无', age:['通用','成人'],
    steps:['背贴墙，双臂屈肘90°贴墙','沿墙向上滑动至最高点再回','12次'], tips:'打开肩关节，改善圆肩。' },

  // —— 有氧训练（补充） ——
  { id:'ex_stair', name:'爬楼梯', cat:'有氧', face:'🪜', target:'心肺/下肢', level:'初级', equip:'楼梯', age:['通用','成人','老年'],
    steps:['中等速度上下楼梯','每次10-15分钟，心率120-140'], tips:'居家有氧，膝痛者扶扶手减量。' },
  { id:'ex_row', name:'划船机', cat:'有氧', face:'🚣', target:'全身心肺', level:'初级', equip:'器械', age:['通用','成人'],
    steps:['腿-髋-臂顺序发力，回放反向','匀速20分钟'], tips:'低冲击全身有氧。' },
  { id:'ex_battlerope', name:'战绳', cat:'有氧', face:'🪢', target:'心肺/肩臂', level:'高级', equip:'战绳', age:['青少年','成人'],
    steps:['半蹲握绳两端，上下交替甩动','30秒×6组'], tips:'高强度间歇，减脂高效。' },
  { id:'ex_zumba', name:'健身操/Zumba', cat:'有氧', face:'💃', target:'心肺/协调', level:'初级', equip:'无', age:['通用','成人','老年'],
    steps:['跟随音乐节奏做有氧舞蹈动作','每次30-45分钟'], tips:'趣味性强，易坚持。' },
  { id:'ex_incline', name:'爬坡走', cat:'有氧', face:'⛰️', target:'心肺/臀腿', level:'初级', equip:'跑步机/坡道', age:['通用','老年','成人'],
    steps:['坡度8-12°，快走','30分钟以上'], tips:'比平路更燃脂且护膝。' },

  // —— 体能训练（分年龄段，补充） ——
  { id:'ex_obstacle', name:'障碍跑', cat:'体能', face:'🚧', target:'灵敏/协调', level:'初级', equip:'标志桶', age:['儿童','青少年'],
    steps:['绕桩/跨栏/钻洞组合路线','计时往返2-3组'], tips:'儿童趣味灵敏训练。' },
  { id:'ex_hopscotch', name:'跳房子', cat:'体能', face:'⬛', target:'协调/平衡', level:'初级', equip:'粉笔', age:['儿童'],
    steps:['单双脚交替跳格','变化路线与节奏'], tips:'传统游戏化体能。' },
  { id:'ex_shuttle', name:'折返跑', cat:'体能', face:'🔁', target:'速度/灵敏', level:'中级', equip:'标志桶', age:['青少年','成人'],
    steps:['5米×5次折返，记录时间','3-4组间隔休息'], tips:'提升变向速度。' },
  { id:'ex_broadjump', name:'立定跳远', cat:'体能', face:'🦘', target:'爆发/下肢', level:'初级', equip:'无', age:['儿童','青少年'],
    steps:['预摆下蹲，蹬地向前跳','5次×3组'], tips:'发展下肢爆发力。' },
  { id:'ex_medball', name:'药球砸', cat:'体能', face:'⚡', target:'全身爆发', level:'高级', equip:'药球', age:['青少年','成人'],
    steps:['过头举球，奋力下砸','接弹起重复，10次×3'], tips:'释放式核心爆发。' },
  { id:'ex_taichi', name:'太极拳', cat:'体能', face:'☯️', target:'平衡/柔韧', level:'初级', equip:'无', age:['老年','通用'],
    steps:['学练简化24式或八段锦','每日20-30分钟'], tips:'老人身心兼修，防跌倒。' },
  { id:'ex_toewalk', name:'踮脚走', cat:'体能', face:'🤸', target:'平衡/踝', level:'初级', equip:'无', age:['老年','通用'],
    steps:['提踵沿直线缓慢行走','每次2-3分钟'], tips:'提升静态平衡。' },
  { id:'ex_seatedleg', name:'坐姿抬腿', cat:'体能', face:'🪑', target:'腿力', level:'初级', equip:'椅子', age:['老年'],
    steps:['坐椅伸直单腿停留3秒','每侧10次×3'], tips:'老人居家练膝伸肌。' },
  { id:'ex_boxjump', name:'跳箱', cat:'体能', face:'📦', target:'下肢爆发', level:'高级', equip:'跳箱', age:['青少年','成人'],
    steps:['半蹲发力跳上箱，稳落再下','8次×4组'], tips:'进阶爆发，注意落地缓冲。' },

  /* ===== 田径运动员专项体能训练 ===== */
  // 核心稳定
  { id:'ex_deadbug2', name:'死虫式', cat:'田径', face:'🐛', target:'核心抗伸展', level:'初级', equip:'无', age:['青少年','成人'],
    steps:['仰卧举臂举腿90°，对侧手脚缓慢下放','保持腰贴地，12次×3组'], tips:'田径核心稳定基础。' },
  { id:'ex_pallof', name:'Pallof 抗旋转', cat:'田径', face:'🌀', target:'核心抗旋转', level:'中级', equip:'弹力带', age:['青少年','成人'],
    steps:['侧向站，双手前推弹力带，保持躯干稳定','30秒×3组，左右轮换'], tips:'强化跑跳中的核心刚度。' },
  { id:'ex_plankdrag', name:'平板拉车', cat:'田径', face:'🛒', target:'核心/肩', level:'中级', equip:'重物', age:['青少年','成人'],
    steps:['平板支撑位，单手拖动身侧重物','保持髋稳定，每侧8-10次'], tips:'抗旋转与上肢稳定。' },
  { id:'ex_hollow', name:'空心体', cat:'田径', face:'🥄', target:'核心整体', level:'中级', equip:'无', age:['青少年','成人'],
    steps:['仰卧，四肢同时抬起，腰贴地','保持20-40秒×3组'], tips:'发展体操式核心张力。' },
  // 下肢力量
  { id:'ex_nordic', name:'北欧挺', cat:'田径', face:'🇸🇪', target:'腘绳肌离心', level:'高级', equip:'同伴/器械', age:['青少年','成人'],
    steps:['跪姿固定踝，身体缓慢前倾，用腘绳肌控制下落','5-8次×3组'], tips:'预防腘绳肌拉伤。' },
  { id:'ex_rdl', name:'罗马尼亚硬拉', cat:'田径', face:'🏋️', target:'腘绳/臀', level:'中级', equip:'杠铃/哑铃', age:['青少年','成人'],
    steps:['微屈膝，屈髋下放至上背平行','臀发力还原，8-10次×3组'], tips:'发展后链力量。' },
  { id:'ex_backsquat', name:'颈后深蹲', cat:'田径', face:'🦵', target:'下肢整体', level:'高级', equip:'杠铃', age:['青少年','成人'],
    steps:['杠铃置斜方肌，下蹲至大腿平行','6-8次×4组'], tips:'下肢力量王牌，需规范技术。' },
  { id:'ex_boxsquat', name:'箱式深蹲', cat:'田径', face:'📦', target:'下肢/爆发力', level:'中级', equip:'箱/凳', age:['青少年','成人'],
    steps:['坐至箱上短暂释放，再爆发站起','8次×3组'], tips:'改善蹲起发力。' },
  { id:'ex_trapjump', name:'负重跳', cat:'田径', face:'⚡', target:'下肢爆发', level:'高级', equip:'杠铃/哑铃', age:['成人'],
    steps:['轻负重半蹲后垂直纵跳','落地缓冲，6次×3组'], tips:'转化力量为爆发力。' },
  { id:'ex_legcurl', name:'腿弯举', cat:'田径', face:'🦶', target:'腘绳肌', level:'中级', equip:'器械', age:['成人'],
    steps:['俯卧或坐姿，屈膝拉负重至小腿垂直','12次×3组'], tips:'孤立强化腘绳肌。' },
  // 髋踝专项
  { id:'ex_anklehop', name:'踝跳', cat:'田径', face:'👣', target:'踝关节刚性', level:'初级', equip:'无', age:['青少年','成人'],
    steps:['原地快速小幅度连续跳','30秒×4组'], tips:'提升踝关节弹性。' },
  { id:'ex_pogos', name:'Pogo 跳', cat:'田径', face:'🦘', target:'踝/小腿弹性', level:'初级', equip:'无', age:['青少年','成人'],
    steps:['双腿或单腿快速弹性跳，触地即起','20次×3组'], tips:'增强牵张反射。' },
  { id:'ex_hurdlehop', name:'栏架跳', cat:'田径', face:'🏃', target:'髋屈/下肢弹性', level:'中级', equip:'栏架', age:['青少年','成人'],
    steps:['连续跳过6-10个矮栏','保持节奏与髋高抬，2-3组'], tips:'提升跨栏与跑跳经济性。' },
  { id:'ex_hiplock', name:'90-90 髋转换', cat:'田径', face:'🧘', target:'髋内外旋灵活', level:'初级', equip:'无', age:['青少年','成人'],
    steps:['坐姿双腿90-90，交替转换前后腿','每侧10次×2组'], tips:'改善髋关节活动度。' },
  { id:'ex_copenhage', name:'哥本哈根支撑', cat:'田径', face:'🇩🇰', target:'内收肌', level:'高级', equip:'凳', age:['青少年','成人'],
    steps:['侧卧，上方腿内收支撑于凳，身体悬空','保持15-30秒×3组，左右轮换'], tips:'预防腹股沟损伤。' },
  // 速度与灵敏
  { id:'ex_accelerate2', name:'短距离加速跑', cat:'田径', face:'🚀', target:'加速能力', level:'中级', equip:'无', age:['青少年','成人'],
    steps:['10-30米全力加速，身体前倾、快速摆臂','4-6组，充分间歇'], tips:'专项速度训练。' },
  { id:'ex_fly', name:' flying 30米', cat:'田径', face:'💨', target:'最高速度', level:'高级', equip:'无', age:['青少年','成人'],
    steps:['30米助跑+30米保持最高速度','4-5组，间歇3-5分钟'], tips:'发展最大速度。' },
  { id:'ex_hillsprint', name:'上坡冲刺', cat:'田径', face:'⛰️', target:'蹬伸力量', level:'中级', equip:'坡道', age:['青少年','成人'],
    steps:['15-30米上坡全力冲刺','6-8组，间歇2-3分钟'], tips:'增强后群与臀肌发力。' },
  { id:'ex_ladder', name:'绳梯训练', cat:'田径', face:'🪜', target:'步频/协调', level:'初级', equip:'绳梯', age:['青少年','成人'],
    steps:['快速小步跑、高抬腿、交叉步通过绳梯','每个动作2-3组'], tips:'提升脚步频率与节奏。' },
  { id:'ex_shuttle2', name:'5-10-5 折返', cat:'田径', face:'🔁', target:'变向灵敏', level:'中级', equip:'标志桶', age:['青少年','成人'],
    steps:['中线起跑，5米左→10米右→5米回中线','计时，3-5组'], tips:'经典灵敏测试与训练。' },
  { id:'ex_bound', name:'跨步跳/单脚跳组合', cat:'田径', face:'🦘', target:'下肢弹性/协调', level:'中级', equip:'无', age:['青少年','成人'],
    steps:['单脚跳→跨步跳→单脚跳循环，30-50米','3-4组'], tips:'发展弹跳与下肢协调。' },
  // 速度耐力
  { id:'ex_tempo2', name:'节奏跑', cat:'田径', face:'🥁', target:'乳酸阈值', level:'中级', equip:'无', age:['青少年','成人'],
    steps:['以稍吃力配速持续跑15-25分钟','心率150-165'], tips:'中长跑基础耐力。' },
  { id:'ex_interval200', name:'200米间歇', cat:'田径', face:'⏱️', target:'速度耐力', level:'高级', equip:'田径场', age:['青少年','成人'],
    steps:['200米×8-10组，间歇2分钟','配速快于比赛配速'], tips:'发展无氧耐力。' },
  { id:'ex_fartlek2', name:'法特莱克跑', cat:'田径', face:'🌲', target:'变速能力', level:'中级', equip:'无', age:['青少年','成人'],
    steps:['慢跑与快跑交替，总距离4-6公里','如快200米+慢100米'], tips:'培养速度感。' },
  { id:'ex_temporun', name:'Tempo 持续跑', cat:'田径', face:'🏃', target:'有氧耐力', level:'初级', equip:'无', age:['青少年','成人'],
    steps:['中等强度持续跑20-40分钟','能完整说短句即可'], tips:'建立有氧基础。' },
  // 恢复再生
  { id:'ex_foamroll', name:'泡沫轴全身放松', cat:'田径', face:'🧽', target:'筋膜放松', level:'初级', equip:'泡沫轴', age:['青少年','成人'],
    steps:['大腿前/后/外侧、小腿、背部缓慢滚动','每部位30-60秒'], tips:'训练后恢复。' },
  { id:'ex_staticstretch', name:'静态拉伸', cat:'田径', face:'🧘', target:'柔韧性', level:'初级', equip:'无', age:['青少年','成人'],
    steps:['腘绳、股四、髋屈、小腿各拉伸30秒','每个动作2组'], tips:'训练后放松。' },
  { id:'ex_breathing', name:'横膈膜呼吸', cat:'田径', face:'🌬️', target:'恢复/副交感', level:'初级', equip:'无', age:['通用'],
    steps:['仰卧屈膝，鼻吸4秒→腹膨隆→嘴呼6秒','10次×2组'], tips:'促进恢复与睡眠。' },
];

/* ---------- 2. 体育备课：专项库 ---------- */
App.data.specialties = [
  { id:'track', name:'田径', emoji:'🏃', focus:true,
    units:['跑：快速跑','跳跃：蹲踞式跳远','投掷：侧向掷垒球','班级田径运动会'] },
  { id:'pingpong', name:'乒乓球', emoji:'🏓', focus:true,
    units:['正手攻球','反手推挡','发球与接发球','左推右攻组合'] },
  { id:'basketball', name:'篮球', emoji:'🏀', focus:false,
    units:['运球与传接','原地/行进间投篮','防守脚步','教学比赛'] },
  { id:'gym', name:'体操', emoji:'🤸', focus:false,
    units:['基本体操动作','技巧：前滚翻','支撑跳跃','韵律操'] },
  { id:'wushu', name:'武术', emoji:'🥋', focus:false,
    units:['武术基本功','五步拳','少年拳','武术套路演练'] },
  { id:'swim', name:'游泳', emoji:'🏊', focus:false,
    units:['熟悉水性与呼吸','蛙泳腿','蛙泳臂与配合','水中安全'] },
  { id:'soccer', name:'足球', emoji:'⚽', focus:false,
    units:['控球与运球','传接球','射门','小场地比赛'] },
  { id:'volleyball', name:'排球', emoji:'🏐', focus:false,
    units:['准备姿势与移动','正面双手垫球','上手发球','正面扣球与教学比赛'] },
  { id:'badminton', name:'羽毛球', emoji:'🏸', focus:false,
    units:['握拍与发球','高远球','网前球','基本战术与比赛'] },
  { id:'tennis', name:'网球', emoji:'🎾', focus:false,
    units:['握拍与正手','反手击球','发球','计分与教学比赛'] },
  { id:'aerobics', name:'健美操', emoji:'💃', focus:false,
    units:['基本步伐','手臂组合','大众锻炼标准套路','自编与展示'] },
  { id:'dance', name:'体育舞蹈', emoji:'🕺', focus:false,
    units:['基本站位与架型','华尔兹基本步','恰恰基本步','双人配合与展示'] },
  { id:'taekwondo', name:'跆拳道', emoji:'🥋', focus:false,
    units:['礼仪与基本步法','前踢与横踢','品势（太极一章）','实战基础'] },
  { id:'fencing', name:'击剑', emoji:'🤺', focus:false,
    units:['器械认知与礼仪','基本步法','弓步刺','简单攻防'] },
  { id:'orient', name:'定向越野', emoji:'🧭', focus:false,
    units:['地图与指北针','打卡流程','路线选择','校园定向赛'] },
  { id:'yoga', name:'瑜伽', emoji:'🧘', focus:false,
    units:['呼吸与坐姿','基础体式','平衡体式','放松与冥想'] },
  { id:'pickleball', name:'匹克球', emoji:'🏓', focus:false,
    units:['握拍与基本站位','正反手颠球与击球','发球与接发球','截击与简单战术','教学比赛'] },
  { id:'baseball', name:'棒垒球', emoji:'⚾', focus:false,
    units:['传接球与握法','击球','跑垒','简单战术与游戏'] },
  { id:'fitness', name:'健身/体能', emoji:'🏋️', focus:false,
    units:['体能测试方法','力量训练基础','速度与灵敏','体能循环设计'] },
];

/* ---------- 3. 体育新闻：样例缓存（联网后拉取真实新闻替换） ---------- */
App.data.newsSeed = [
  { id:'n1', src:'国家', tag:'政策', title:'《全民健身计划》持续推进，社区运动场地覆盖率持续提升', date:'2026-07', sum:'国家体育总局持续推进全民健身设施补短板工程，重点建设社区健身中心与步道。' },
  { id:'n2', src:'国家', tag:'赛事', title:'全国学生运动会筹备工作启动，体教融合成重点', date:'2026-07', sum:'聚焦体教融合，增设校园组，强调文化学习与体育锻炼协调发展。' },
  { id:'n3', src:'上海', tag:'本地', title:'上海发布：年内新增社区市民健身中心，打通"最后一公里"', date:'2026-07', sum:'上海市体育局联合各区推进市民健身中心布局，打造15分钟社区体育生活圈。' },
  { id:'n4', src:'上海', tag:'校园', title:'上海校园体育"一条龙"人才培养体系建设加快', date:'2026-07', sum:'贯通小初高体育人才选育，篮球、田径、游泳等项目试点布局。' },
  { id:'n5', src:'国家', tag:'科研', title:'体育总局发布青少年体质健康干预指南', date:'2026-06', sum:'针对近视、肥胖、体态不良提出运动干预处方建议。' },
  { id:'n6', src:'上海', tag:'赛事', title:'上海马拉松报名启动，增设亲子跑与健身跑组别', date:'2026-06', sum:'赛事扩容，强调全民参与与安全完赛。' },
  { id:'n7', src:'国家', tag:'产业', title:'体育消费季启动，发放运动消费券', date:'2026-06', sum:'多省市联动促体育消费，覆盖场馆、装备与培训。' },
  { id:'n8', src:'上海', tag:'健康', title:'上海推进"体医融合"慢病运动干预门诊', date:'2026-05', sum:'部分社区医院开设运动干预门诊，由运动处方师开具个性化方案。' },
];

/* ---------- 4. 科研：真实文献种子（来自 Europe PMC，含摘要，附方法/结果/结论总结） ---------- */
App.data.researchSeed = [
  { id:'r1', topic:'训练', title:'Exercise Guidelines for Cancer Survivors: Consensus Statement',
    authors:'Campbell KL, Winters-Stone KM, Wiskemann J 等', journal:'Med Sci Sports Exerc', year:2019,
    pmcid:'PMC8576825', doi:'10.1249/mss.0000000000002116',
    abstract:'Purpose: 全球癌症幸存者增多且面临独特健康挑战。Methods: 2018年召开第二届多学科圆桌会议，在前述ACS指南基础上制定针对癌症类型、治疗方式与结局的处方化运动建议。Results: 运动对癌症幸存者总体安全；有氧、抗阻及联合训练可改善焦虑、抑郁、疲劳、身体功能与生活质量。Conclusions: 提出针对癌症幸存者的运动处方建议，作为健身与健康从业者的指南。',
    method:'2018年召开第二届国际多学科圆桌会议，在前述美国运动医学会(ACSM)指南基础上，针对具体癌症类型、治疗方式与结局，制定处方化（剂量化）运动建议。',
    result:'结论保留：运动训练与测试对癌症幸存者总体安全；特定剂量的有氧、有氧+抗阻、抗阻训练可改善焦虑、抑郁症状、疲劳、身体功能与健康相关生活质量。',
    conclusion:'提出面向癌症幸存者的运动处方建议，作为健身与医疗工作者的实践指南；仍须研究填补神经病变、认知功能等结局的证据空白。',
    link:'https://europepmc.org/article/PMC/PMC8576825' },

  { id:'r2', topic:'训练', title:'Lack of exercise is a major cause of chronic diseases',
    authors:'Booth FW, Roberts CK, Laye MJ', journal:'Comprehensive Physiology', year:2012,
    pmcid:'PMC4241367', doi:'10.1002/cphy.c110025',
    abstract:'慢性病患者现代主要死因。身体活动不足是大多数慢病的主要成因。本文界定活动与预防概念，分析基因-环境交互（含有氧训练适应、个性化医学）与训练特异性适应，并将运动作为35种慢病（肥胖、2型糖尿病、心血管病、部分癌症、骨质疏松等）的一级预防；结论：身体对活动不足会快速适应不良，显著缩短健康寿命；缺乏身体活动是多数慢病的重要成因，而运动主要起预防/延迟作用。',
    method:'综述：界定身体活动/预防概念，梳理历史证据、因果与治疗的区别、基因-环境交互（含有氧训练适应与个性化医学）及训练类型的特异性适应。',
    result:'列举身体活动不足作为35种慢病（加速衰老、低心肺适能、肌少症、代谢综合征、肥胖、2型糖尿病、心血管病、部分癌症、骨质疏松、抑郁焦虑等）的主要成因；有氧训练产生可测量的个性化生理适应。',
    conclusion:'缺乏身体活动是多数慢病的重要成因；身体活动主要起预防或延迟慢病的作用，故慢病并非生命中必然结果。',
    link:'https://europepmc.org/article/PMC/PMC4241367' },

  { id:'r3', topic:'体态/减脂', title:'Waist circumference as a vital sign in clinical practice',
    authors:'Ross R, Neeland IJ, Yamashita S 等', journal:'Nat Rev Endocrinol', year:2020,
    pmcid:'PMC7027970', doi:'10.1038/s41574-019-0310-7',
    abstract:'尽管数十年证据表明腰围较BMI提供独立且附加的发病/死亡风险信息，临床仍非常规测量。本共识提出将腰围测量作为改善患者管理的重要机会；论证BMIalone不足以评估肥胖相关心肺代谢风险，并综述支持常规纳入腰围的证据；建议将腰围下降作为减脂的重要治疗靶点；中等强度运动/饮食可显著降低腰围。',
    method:'共识声明：综述腰围相对BMI在预测发病与死亡风险中的独立附加价值证据，评估不同BMI分层下腰围阈值的优化空间。',
    result:'腰围可提供独立于BMI的额外风险信息；临床相关幅度的腰围下降可通过常规中等强度运动及/或饮食干预实现。',
    conclusion:'建议将腰围作为临床"生命体征"常规测量并培训医务人员；将腰围下降作为减脂的重要治疗靶点。',
    link:'https://europepmc.org/article/PMC/PMC7027970' },

  { id:'r4', topic:'康复', title:'Exercise for preventing falls in older people living in the community',
    authors:'Sherrington C, Fairhall NJ, Wallbank GK 等', journal:'Cochrane Database Syst Rev', year:2019,
    pmcid:'PMC6360922', doi:'10.1002/14651858.cd012424.pub2',
    abstract:'Background: 65岁以上社区老人每年至少1/3跌倒。Objectives: 评估运动干预预防跌倒的效果与危害。Methods: 检索至2018-05，纳入60岁以上社区老人的RCT。Results: 纳入108项RCT（23407人）。运动使跌倒率降低23%（高确定性），跌倒人数降低15%；平衡与功能训练降跌倒率24%，多类型运动降34%，太极拳可能降19%。Conclusions: 以平衡与功能训练为主的运动方案可有效降低社区老人跌倒率。',
    method:'Cochrane系统综述与Meta分析：检索CENTRAL/MEDLINE/Embase等至2018-05，纳入以运动为单一干预、针对60岁以上社区老人的随机对照试验(RCT)，主要结局为跌倒发生率。',
    result:'共108项RCT、23407名受试者（平均76岁，77%女性）。运动使跌倒率降低23%（高确定性证据），经历≥1次跌倒的人数降低15%；平衡与功能训练降跌倒率24%，多类型（平衡+抗阻）运动降34%，太极拳可能降19%。',
    conclusion:'运动方案可降低社区老人跌倒率与跌倒人数（高确定性）；以平衡与功能训练为主，多类型运动效果更佳。',
    link:'https://europepmc.org/article/PMC/PMC6360922' },

  { id:'r5', topic:'训练', title:'Health benefits of physical activity: the evidence',
    authors:'Warburton DE, Nicol CW, Bredin SS', journal:'CMAJ', year:2006,
    pmcid:'PMC1402378', doi:'10.1503/cmaj.051351',
    abstract:'目的：评估现有文献并阐述身体活动不足在慢病与早死中的作用。我们确认规律体力活动在心血管病、糖尿病、癌症、高血压、肥胖、抑郁、骨质疏松等慢病一级与二级预防中有效的证据确凿；现有加拿大体力活动指南足以带来健康收益，尤其对既往久坐者；体力活动与健康呈近似线性关系，进一步增加活动与适能会带来额外改善。',
    method:'叙述性综述：系统评估规律体力活动在多种慢病一级与二级预防中的现有文献证据。',
    result:'规律运动对心血管病、糖尿病、癌症、高血压、肥胖、抑郁、骨质疏松等预防效果确凿；体力活动水平与健康状态呈近似线性关系。',
    conclusion:'现有指南足以带来健康收益，尤其对既往久坐人群；进一步增加活动与适能可带来额外健康改善。',
    link:'https://europepmc.org/article/PMC/PMC1402378' },

  { id:'r6', topic:'康复/老年', title:'Sarcopenia: Aging-Related Loss of Muscle Mass and Function',
    authors:'Larsson L, Degens H, Li M 等', journal:'Physiological Reviews', year:2019,
    pmcid:'PMC6442923', doi:'10.1152/physrev.00061.2017',
    abstract:'肌少症是老年肌肉量与功能丢失，降低活动能力、增加跌倒与昂贵康复风险。本综述聚焦运动单位（α运动神经元胞体、神经肌肉接头、所支配肌纤维）增龄性结构与细胞/亚细胞机制改变；肌少症主要因运动神经元进行性丢失导致肌纤维数量与体积下降，再支配不足致功能下降；细胞内蛋白翻译后修饰改变与收缩/线粒体/肌浆网蛋白表达失调也参与。',
    method:'综述：从细胞与亚细胞层面分析增龄相关的运动单位（α运动神经元、神经肌肉接头、肌纤维）结构改变与机制。',
    result:'肌少症主要因运动神经元进行性丢失、肌纤维数量与体积下降；再支配不足致肌肉功能渐进下降；蛋白修饰与线粒体/肌浆网蛋白表达失调参与。',
    conclusion:'针对神经肌肉的可行干预策略在实验模型中显示延缓运动单位结构与功能退化的前景，若转化临床有望减轻老年肌少症并带来巨大健康与经济价值。',
    link:'https://europepmc.org/article/PMC/PMC6442923' },

  { id:'r7', topic:'康复', title:'Osteoarthritis: pathogenic signaling pathways and therapeutic targets',
    authors:'Yao Q, Wu X, Tao C 等', journal:'Sig Transduct Target Ther', year:2023,
    pmcid:'PMC9898571', doi:'10.1038/s41392-023-01330-w',
    abstract:'骨关节炎(OA)是影响全球超5亿人的慢性退行关节病。现被视为累及全关节的慢病，始于滑膜关节组织的生化与细胞改变，最终导致整体组织功能障碍；目前尚无治愈方法。本综述总结OA流行病学与Wnt/β-catenin、NF-κB、TGFβ/BMP、mTOR等信号通路及MMP、ADAMTS、PRG4等关键因子，并更新临床治疗与生物制剂试验进展。',
    method:'综述：总结OA流行病学、Wnt/β-catenin、NF-κB、黏附斑、HIF、TGFβ/BMP、FGF等病理信号通路，以及MMP、ADAMTS、PRG4等关键调节因子，并梳理临床治疗与试验。',
    result:'OA是累及全关节的退行性疾病，多信号通路参与其发生发展；现有治疗多为对症，缺乏根治手段。',
    conclusion:'深入解析OA病理通路与关键分子，对治疗靶点设计与药物开发具重要转化价值。',
    link:'https://europepmc.org/article/PMC/PMC9898571' },
];
